### ISSUE TITLE
Add support for vnd.oci.image.index.v1+json type manifest

### ISSUE THREAD

**Issue by zeroalphat** [Hsn723/container-tag-exists#20]
Since buildx v0.10.0, the manifests pushed to the registry are now of a different type, and `container-tag-exists` does not properly determine if a tag exists.

```
# buildx v0.9
zeroalphat@host-vm ~> GITHUB_TOKEN=$GITHUB_TOKEN container-tag-exists ghcr.io/cybozu/ubuntu 22.04.20230209
found

# buildx v0.10.0
zeroalphat@host-vm ~> GITHUB_TOKEN=$GITHUB_TOKEN container-tag-exists ghcr.io/cybozu/ubuntu 22.04.20230208
```

The reason for this is that the type of manifests pushed has changed, so manifests can no longer be retrieved with the traditional `application/vnd.docker.distribution.manifest.v2+json` header.
```
zeroalphat@host-vm ~> curl -s --header "Authorization: Bearer $BEARER" \
                                 --header "Accept: application/vnd.docker.distribution.manifest.v2+json" https://ghcr.io/v2/cybozu/ubuntu/manifests/22.04.20230208 | jq .
{
  "errors": [
    {
      "code": "MANIFEST_UNKNOWN",
      "message": "OCI index found, but Accept header does not support OCI indexes"
    }
  ]
}
```

To get a manifest from the registry, I had to use `application/vnd.oci.image.index.v1+json` header.
```
zeroalphat@host-vm ~> curl -s --header "Authorization: Bearer $BEARER" \
                                 --header "Accept: application/vnd.oci.image.index.v1+json" https://ghcr.io/v2/cybozu/ubuntu/manifests/22.04.20230208 | jq .
{
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "schemaVersion": 2,
  "manifests": [
```

Is it the possible to support `vnd.oci.image.index.v1+json` media type manifest.

**Comment by Hsn723** [comment]
@zeroalphat 
Thank you for your report. It looks like `Accept: application/vnd.oci.image.index.v1+json` can also be used to retrieve existing manifests, so we can simply have `container-tag-exists` use that header going forward.

**Comment by zeroalphat** [comment]
Thank you for the quick fix!
